# Tutorial 8 - Python Numpy Array

# Numpy tutorials

  Numpy is general purpose array-processing package. Its provides a high-performance multi-dimentional array object, and tools for working with these arrays. It is the fundamental package for scintific computing with python


# What is an array 

  An array is a data structure that stores value of sample data type. In Python, this is the main difference between arrays and lists. While python lists can contains value corresponding to different data type. 

In [2]:
## import the library

import numpy as np


In [4]:
lst = [1,2,3,4]
arr = np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [8]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]

In [13]:
arr1 = np.array([lst1,lst2,lst3])
arr1.shape


(3, 5)

In [15]:
# array can get using index and also change value
arr

array([1, 2, 3, 4])

In [16]:
arr[3]

np.int64(4)

In [17]:
arr[1:]

array([2, 3, 4])

In [18]:
arr[-1]

np.int64(4)

In [19]:
arr[:-1]

array([1, 2, 3])

In [20]:
arr[::-1]

array([4, 3, 2, 1])

In [22]:
arr1[:,0]

array([1, 2, 3])

In [24]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [25]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [28]:
arr1[1:,3:5]

array([[5, 6],
       [6, 7]])

In [29]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [30]:
# EDA
arr

array([1, 2, 3, 4])

In [32]:
arr[arr < 2]

array([1])

In [33]:
arr1.shape

(3, 5)

In [34]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [35]:
 # mechanism to create an array

In [36]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
np.arange(0,20,2).reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [48]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.random.randint(10,50)

38

In [55]:
np.random.randint(10,50,4).reshape(2,2)

array([[49, 40],
       [23, 17]], dtype=int32)